#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
APP_SUPPORT="$HOME/Library/Application Support/AgentBackup"
mkdir -p "$APP_SUPPORT"
# Remembers the project ID between runs; holds nothing secret.
ENV_FILE="$APP_SUPPORT/wizard.env"

banner "Agent Backup — connect Google Drive"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Google Cloud project"
say "Agent Backup needs its own OAuth client, which lives in a Google Cloud project."
say "A new, empty project is cleanest. It's free — no billing account needed."
open_url "https://console.cloud.google.com/projectcreate"
step "Project name: agent-backup → Create (or pick an existing project instead)."
step "Copy the Project ID — shown under the name, e.g. agent-backup-123456."
note "Later stages open URLs for this project, so make sure it's the one selected at the top."
ask GOOGLE_CLOUD_PROJECT "Paste the Project ID:"
write_env GOOGLE_CLOUD_PROJECT "$GOOGLE_CLOUD_PROJECT"
P="$GOOGLE_CLOUD_PROJECT"
pause

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Enable the Google Drive API"
open_url "https://console.cloud.google.com/apis/library/drive.googleapis.com?project=$P"
step "Click Enable. (If it says 'Manage' instead, it's already on.)"
pause "Press Enter once the Drive API is enabled"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "OAuth consent screen"
open_url "https://console.cloud.google.com/auth/overview?project=$P"
step "Click Get started. (If you see an overview with Branding/Audience/Clients, it's done — skip.)"
step "App name: Agent Backup · User support email: your Gmail → Next"
step "Audience: External → Next"
step "Contact information: your Gmail → Next → agree to the policy → Create"
pause "Press Enter once the consent screen is created"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Allow the drive.file scope"
say "drive.file lets the app see only files it created itself, never the rest of your Drive."
open_url "https://console.cloud.google.com/auth/scopes?project=$P"
step "Click 'Add or remove scopes'."
step "In the filter, type drive.file and tick  …/auth/drive.file"
step "Click Update, then Save at the bottom of the page."
note "It's a non-sensitive scope, so Google doesn't need to review the app."
pause "Press Enter once the scope is saved"

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Publish the app"
say "While the app is in 'Testing', Google expires your login every 7 days."
open_url "https://console.cloud.google.com/auth/audience?project=$P"
step "Under Publishing status, click 'Publish app' → Confirm."
note "Prefer to stay in Testing? Add your Gmail under 'Test users' instead,"
note "and expect to run 'agent-backup drive login' again every week."
pause "Press Enter once it's published (or you've added yourself as a test user)"

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Create the Desktop OAuth client"
open_url "https://console.cloud.google.com/auth/clients/create?project=$P"
step "Application type: Desktop app · Name: agent-backup → Create"
step "In the dialog that appears, click 'Download JSON'."
warn "Download it now — the console may not show the client secret again later."
pause "Press Enter once the JSON is in your Downloads folder"

DEFAULT_JSON="$(ls -t "$HOME"/Downloads/client_secret_*.json 2>/dev/null | head -n1 || true)"
if [[ -n "$DEFAULT_JSON" ]]; then
  say "Found: $DEFAULT_JSON"
  printf '  %sPath to the JSON%s %s[Enter uses the file above]%s ' "$BOLD" "$RESET" "$DIM" "$RESET"
else
  printf '  %sPath to the downloaded client_secret_….json:%s ' "$BOLD" "$RESET"
fi
read -r CLIENT_JSON || true
CLIENT_JSON="${CLIENT_JSON:-$DEFAULT_JSON}"
CLIENT_JSON="${CLIENT_JSON/#\~/$HOME}"
[[ -f "$CLIENT_JSON" ]] || { warn "No file at '$CLIENT_JSON'. Re-run the wizard once it's downloaded."; exit 1; }

say "Building agent-backup (first build takes a minute)…"
(cd "$REPO_ROOT" && swift build --product agent-backup >/dev/null)
BIN="$(cd "$REPO_ROOT" && swift build --show-bin-path)/agent-backup"
"$BIN" drive setup --client-json "$CLIENT_JSON" | sed 's/^/  /'
if confirm "Delete the downloaded copy ($CLIENT_JSON)? The app keeps its own."; then
  rm -f "$CLIENT_JSON"
  printf '  %s✓ deleted%s %s\n' "$GREEN" "$RESET" "$CLIENT_JSON"
fi
pause

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Log in and check the connection"
say "Your browser will open. Pick your Google account and allow access."
note "If you see 'Google hasn't verified this app': Advanced → Go to Agent Backup."
note "That's expected — it's your own app, made a minute ago."
"$BIN" drive login
"$BIN" drive status | sed 's/^/  /'
pause

finish
say "Next: back up to Google Drive (the first run asks you to choose a passphrase):"
say "  $BIN backup --to gdrive"
printf '\n'
